// Central source of truth for the scroll-driven image sequence.
// Optimized frames live in /public/frames-webp as ezgif-frame-001.webp ...
// ezgif-frame-208.webp (generated by scripts/optimize-images.mjs from the
// original PNGs in /public/frames). To swap footage: drop new PNGs in
// /public/frames, re-run the script, and update FRAME_COUNT below.

export const FRAME_COUNT = 208;
export const FRAME_EXT = 'webp';
const FRAME_DIR = '/frames-webp';

// Number of frames to fully decode before lifting the splash. Kept small: the
// canvas only needs the opening frames to be interactive, and the streamer
// draws the nearest-loaded neighbour for anything still in flight, so the
// splash lifts fast and the rest buffers ahead during the first scroll.
export const INITIAL_FRAME_BATCH = 8;

const pad = (n: number): string => String(n).padStart(3, '0');

/** Public URL for a 1-based frame index. */
export const frameUrl = (index: number): string =>
  `${FRAME_DIR}/ezgif-frame-${pad(index)}.${FRAME_EXT}`;

/** All frame URLs, 1-based order. */
export const frameUrls: string[] = Array.from({ length: FRAME_COUNT }, (_, i) =>
  frameUrl(i + 1)
);
